### ISSUE TITLE
Issue launching because of icon

### ISSUE THREAD

**Issue by n1kk0s** [n1kk0s/ChromeExtension#2]
For some reason Chrome won't allow me to run it. It runs into a problem in the manifest.json file where it sets the default_icon to icon.png

**Comment by n1kk0s** [comment]
So, I lied. It runs it, but it still doesn't show the icon

**Comment by banrahan** [comment]
Oh, I think I deleted the icon? Is it still there...that may have been me

**Comment by n1kk0s** [comment]
You're good, it's still there. I just double checked and the icon's working fine. I just closed it since I thought it was working now.
